// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleSignalR;

namespace SimpleSignalR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180602170541_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("SimpleSignalR.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Owner");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new { Id = 1, Content = "Cool", Owner = "Negev" },
                        new { Id = 2, Content = "Badio", Owner = "Adawg" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
